In [1]:
import numpy as np


def task_6():
    try:
        arr = np.array([int(i) for i in input('Enter array separated by spaces: ').strip().split(' ')])
    except ValueError:
        print('Incorrect array')
    else:
        new_arr = np.where(arr != 0, np.array([-1]), arr)
        print('Array: ', new_arr)


def task_7():
    try:
        arr = np.array([int(i) for i in input('Enter array separated by spaces: ').strip().split(' ')])
    except ValueError:
        print('Incorrect array')
    else:
        new_arr = np.where(arr == 0, np.array([-1]), arr)
        print('Array: ', new_arr)


def task_9():
    try:
        n = int(input('Enter positive number: '))
        if n <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect number!')
    else:
        arr = np.arange(n, -1, -1)
        print('Array: ', arr)


def task_10():
    try:
        n, m = [int(i) for i in input('Enter 2 positive numbers separated by spaces: ').strip().split(' ')]
        if n <= 0 or m <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect numbers')
    else:
        arr = np.random.rand(m, n)
        print('Array:\n', arr)
        print('min: ', np.round(np.min(arr), 3))
        print('max: ', np.round(np.max(arr), 3))
        print('mean: ', np.round(np.mean(arr), 3))
        print('deviation: ', np.round(np.std(arr), 3))


def task_11():
    try:
        n = int(input('Enter positive number: '))
        if n <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect number')
    else:
        x = np.ones((n, n))
        x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
        print(x)


def task_15():
    # n is twice smaller then board size
    n = 4
    if n >= 0:
        checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (n, n))
        print(checkerboard)
    else:
        print('n is incorrect', n)


def task_17():
    try:
        n = int(input('Enter positive number: '))
        if n <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect number')
    else:
        arr = np.arange(n + 1)
        print('Array: ', arr)
        new_arr = np.where(((arr >= n / 2) & (arr <= 3 * n / 4)), np.array([0]), arr)
        print('Replace all values greater than n/2 and less than 3n/4 with zeros: n =', n)
        print(new_arr)


def task_18():
    try:
        n = int(input('Enter positive number: '))
        if n <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect number')
    else:
        arr = np.arange(n + 1)
        print('Array: ', arr)
        new_arr = np.where(((arr < n / 2) | (arr > 3 * n / 4)), -arr, arr)
        print(' Replace signs for all values less than n/2 and greater than 3n/4 to opposite ones: n =', n)
        print(new_arr)


def task_20():
    try:
        n = int(input('Enter positive number: '))
        if n <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect number')
    else:
        arr = np.round(np.linspace(0.0, 1.0, num=n + 1, endpoint=False)[1:], 3)
        print('Array: ', arr)


def task_22():
    try:
        n, m = [int(i) for i in input('Enter 2 positive numbers separated by spaces: ').strip().split(' ')]
        if n <= 0 or m <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect numbers')
    else:
        arr = np.random.randint(0, m, (n, n))
        print('Initial vector\n', arr)
        new_arr = np.where(arr == np.max(arr), -arr, arr)
        print('Modified vector\n', new_arr)

Excercise 6. An array is entered from the keyboard. Replace all non-zero elementswith -1.<br>
Excercise 7. An array is entered from the keyboard. Replace all zeros with -1.<br>
Excercise 9. Enter the number n. Create an array of values from n to 0.<br>
Excercise 10. Enter the numbers n and m. Create an array of random values of size
nхn and calculate the minimum, maximum value, mean and standard deviation, rounded to 3 decimal places.<br>
Excercise 11. Create an array of 1 of size nхn and add to it a "border" formed from 0.<br>
Excercise 15. Arrange 1 and 0 on the 8х8 field in a checkerboard pattern using the numpy tile().<br>
Excercise 17. Fill the vector with values from 0 to n. Replace all values greater than n/2 and less than 3n/4 with zeros.<br>
Excercise 18. Fill the vector with values from 0 to n. Replace signs for all values less than n/2 and greater than 3n/4 to opposite ones.<br>
Excercise 20. Generate a vector of n elements that are evenly spaced on the interval (0,1) i.e. both ends of the interval are not included. Output values up to 3 decimal places.<br>
Excercise 22. Enter the numbers n and m. Generate a matrix nхn of random integer elements from 0 to m. Change the signs of all maximum elements to the opposite.<br> 

In [2]:
task_6()

Enter array separated by spaces: 0 5 4 3 8 5 0 5 0 4 0 69 0
Array:  [ 0 -1 -1 -1 -1 -1  0 -1  0 -1  0 -1  0]


In [3]:
task_7()

Enter array separated by spaces: 0 5 4 3 8 5 0 5 0 4 0 69 0
Array:  [-1  5  4  3  8  5 -1  5 -1  4 -1 69 -1]


In [4]:
task_9()

Enter positive number: 15
Array:  [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [5]:
task_10()

Enter 2 positive numbers separated by spaces: 4 5
Array:
 [[0.32801093 0.46267726 0.74588901 0.05553454]
 [0.68236559 0.17805098 0.51982709 0.94596453]
 [0.95538662 0.05427486 0.22276202 0.39078616]
 [0.33795202 0.80543414 0.67778407 0.61189078]
 [0.58399779 0.15034977 0.36387    0.10867954]]
min:  0.054
max:  0.955
mean:  0.459
deviation:  0.278


In [6]:
task_11()

Enter positive number: 4
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:
task_15()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
task_17()

Enter positive number: 10
Array:  [ 0  1  2  3  4  5  6  7  8  9 10]
Replace all values greater than n/2 and less than 3n/4 with zeros: n = 10
[ 0  1  2  3  4  0  0  0  8  9 10]


In [9]:
task_18()

Enter positive number: 10
Array:  [ 0  1  2  3  4  5  6  7  8  9 10]
 Replace signs for all values less than n/2 and greater than 3n/4 to opposite ones: n = 10
[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]


In [10]:
task_20()

Enter positive number: 10
Array:  [0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


In [12]:
task_22()

Enter 2 positive numbers separated by spaces: 4 5
Initial vector
 [[0 4 4 2]
 [0 2 1 4]
 [4 4 4 1]
 [2 4 1 4]]
Modified vector
 [[ 0 -4 -4  2]
 [ 0  2  1 -4]
 [-4 -4 -4  1]
 [ 2 -4  1 -4]]
